#!/bin/bash
set -euo pipefail

# sphinx-multiversion runs this script from each temporary checkout. This
# branch-owned wrapper only selects the Java runtime; the actual Javadocs are
# still generated by the checkout's own docs/_utils/javadoc.sh so historical
# refs keep their branch-local docs and Maven configuration.

version_name="${SPHINX_MULTIVERSION_NAME:-unknown}"

if [[ "${version_name}" == scylla-* || "${version_name}" == tags/* ]]; then
    if [[ -z "${JAVA_HOME_8_X64:-}" ]]; then
        echo "JAVA_HOME_8_X64 is required to build historical docs for ${version_name}" >&2
        exit 1
    fi

    export JAVA_HOME="$JAVA_HOME_8_X64"
    export PATH="$JAVA_HOME/bin:$PATH"
    echo "Using Java 8 for historical docs version ${version_name}"
elif [[ -n "${JAVA_HOME_11_X64:-}" ]]; then
    export JAVA_HOME="$JAVA_HOME_11_X64"
    export PATH="$JAVA_HOME/bin:$PATH"
    echo "Using Java 11 for ${version_name}"
fi

echo "Building Javadocs for ${version_name} with Java:"
java -version

bash -e ./docs/_utils/javadoc.sh
