name: "Docs / Build PR"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  pull_request:
    branches:
    - scylla-4.x
    paths:
    - 'docs/**'
    - 'faq/**'
    - 'manual/**'
    - 'changelog/**'
    - 'upgrade_guide/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up env
        run: make -C docs setupenv
      - name: Build docs
        run: make -C docs test
