name: "Docs / Build PR"

on:
  pull_request:
    branches:
    - scylla-3.x
    paths:
    - 'docs/**'
    - 'faq/**'
    - 'manual/**'
    - 'changelog/**'
    - 'upgrade_guide/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build docs
      run: make -C docs test