name: Re-release ScyllaDB Java Driver

on:
  workflow_dispatch:
    inputs:
      version_tag:
        type: string
        description: ''
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      MVNCMD: mvn -B -X -ntp

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Checkout Code One Commit Before ${{ inputs.version_tag }}
      run: |
        git fetch --prune --unshallow || true
        git checkout ${{ inputs.version_tag }}~1
        git tag -d ${{ inputs.version_tag }}

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: ossrh
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD

    - name: Configure Git user
      run: |
        git config user.name "ScyllaDB Promoter"
        git config user.email "github-promoter@scylladb.com"

    - name: Clean project
      run: $MVNCMD clean

    - name: Clean release
      run: $MVNCMD release:clean

    - name: Prepare release
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: $MVNCMD release:prepare -DskipTests -Darguments="-DskipTests" -DpushChanges=false -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

    - name: Perform release
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: $MVNCMD release:perform -DscmSkip=true -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
