name: Tests

on:
  push:
    branches: [ scylla-3.*x ]
  pull_request:
    branches: [ scylla-3.*x ]

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Run unit tests
        run: mvn -B test

  run-cassandra-integration-tests:
    name: Run integration tests on Cassandra
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup environment (Integration test on Cassandra 3.11.11)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python-is-python3 python3-boto3
          sudo pip3 install https://github.com/scylladb/scylla-ccm/archive/master.zip

      - name: Run integration tests on Cassandra 3.11.11
        run: mvn -B verify -Pshort -Dcassandra.version=3.11.11

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: ccm-logs-cassandra-3.11.11
          path: /tmp/*-0/ccm*/node*/logs/*

  run-scylla-integration-tests:
    name: Run integration tests on Scylla
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scylla-version: ['4.4.4', '4.3.6']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup environment (Integration test on Scylla ${{ matrix.scylla-version }})
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python-is-python3 python3-boto3
          sudo pip3 install https://github.com/scylladb/scylla-ccm/archive/master.zip
          sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"

      - name: Run integration tests on Scylla (${{ matrix.scylla-version }})
        run: mvn -B verify -Pshort -Dscylla.version=${{ matrix.scylla-version }}

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: ccm-logs-scylla-${{ matrix.scylla-version }}
          path: /tmp/*-0/ccm*/node*/logs/*